### ISSUE TITLE
Configure login button text

### ISSUE THREAD

**Issue by sknolin** [YoitoFes/dokuwiki-plugin-oauthkeycloak#1]
I want to configure the text of the login button.

It looked to me that it should be set in the oauth plugin, but apparently needs to be implemented vi getLabel() in this plugin?
[doukiwiki-plugin-oauth issue 124](https://github.com/cosmocode/dokuwiki-plugin-oauth/issues/124)

Thanks for any help.

**Comment by YoitoFes** [comment]
Made login button text configurable.

You can update the plugin and test it.

**Comment by sknolin** [comment]
I tested and it works perfectly, thank you very much.
