### ISSUE TITLE
Is not possible to used with a keycloak in https auto-signed configuration

### ISSUE THREAD

**Issue by gschnellOnera** [YoitoFes/dokuwiki-plugin-oauthkeycloak#4]
I used auto signed certificate to make sone integration test.

I modify the /dokuwiki/inc/HTTP/HTTPClient.php file to pass the ssl certificate verification with at line 257:

```
        if (is_null($socket) || feof($socket)) {
           $this->debug('opening connection', $connectionId);
           $context = stream_context_create([
             'ssl' => [
                 'verify_peer' => false,
                 'verify_peer_name' => false
               ]
             ]);
            // open socket
            //$socket = @fsockopen($server,$port,$errno, $errstr, $this->timeout);
            $socket = @stream_socket_client($connectionId,$errno, $errstr, $this->timeout, STREAM_CLIENT_CONNECT, $context);
            if (!$socket){
                $this->status = -100;
                $this->error = "Could not connect to $server:$port '$errstr' ($errno)";
                return false;
            }
```
And it's work
But the modification is very bad
I propose to add an option for no verify certificate.

**Comment by YoitoFes** [comment]
IMO it requires `dokuwiki\HTTP\DokuHTTPClient`、`dokuwiki\HTTP\HTTPClient`、`dokuwiki\plugin\oauth\HTTPClient` classes to support no verify certificate option. Issues should be opened at https://github.com/splitbrain/dokuwiki and https://github.com/cosmocode/dokuwiki-plugin-oauth

**Comment by gschnellOnera** [comment]
Issu report in: https://github.com/splitbrain/dokuwiki/issues/3713
