### ISSUE TITLE
Error 400 after inactivity

### ISSUE THREAD

**Issue by tank0226** [YoitoFes/dokuwiki-plugin-oauthkeycloak#5]
I have integrated Dokuwiki with Keycloak OpenID Connect and sign-in/out works perfectly.

However if I login to Dokuwiki and leave the session idle, upon return Dokuwiki will throw an error.

`OAuth: An error occured during the request to the oauth provider: [HTTP 400]`

I suspect that the access token has expired and there is an error when refreshing the token. My session settings are default:

SSO Session Idle: 30m
SSO Session Max: 10h
Offline Session Idle: 30d

I am also using the same Keycloak realm with applications like Gitea, oauth2-proxy and do not face the same issue.

Versions
bitnami/keycloak:19.0.3
bitnami/dokuwiki:20220731.1.0
plugin:oAuth (2022-03-28)
plugin:oauthkeycloak (2022-03-17)

Also reported at https://github.com/cosmocode/dokuwiki-plugin-oauth/issues/122

**Comment by tank0226** [comment]
Upon examining Keycloak logs, seems like my other applications (Gitea, oauth2-proxy) do not respect the session idle and no request is made to Keycloak even after 30m idle. Only Dokuwiki does it and hit the error.
![IMG-20221123-WA0010](https://user-images.githubusercontent.com/32258476/203476423-49664d60-cc15-444f-965d-30ccc3326669.jpg)

**Comment by YoitoFes** [comment]
Dokuwiki processes Oauth2 Token at [dokuwiki\plugin\oauth\Service\AbstractOAuth2Base::parseAccessTokenResponse()](https://github.com/cosmocode/dokuwiki-plugin-oauth/blob/master/Service/AbstractOAuth2Base.php#L17) and ignores the refresh token life span.

IMO, to fix this issue requires dokuwiki-plugin-oauth to support life span of refresh tokens.

**Comment by tank0226** [comment]
After tweaking some settings, I think I have figured out how Dokuwiki does things under the hood.

Dokuwiki ignores the lifespan of refresh token (default dictated by Keycloak's SSO Session Idle of 30m).
It even ignores the lifespan of access token (default dictated by Keycloak's Access Token Lifespan of 5m).

Dokuwiki only care about [auth_security_timeout](https://www.dokuwiki.org/config:auth_security_timeout). Whenever this period elapse, any page load of Dokuwiki will trigger a call Keycloak to refresh the access token (regardless of access token validity).
This means that the HTTP 400 error is actually valid indicating the SSO session (refresh token) has expired.

Therefore auth_security_timeout should closely match the lifespan of access token so they are regularly refreshed.
