### ISSUE TITLE
Three Errors on first login

### ISSUE THREAD

**Issue by spacecake** [YoitoFes/dokuwiki-plugin-oauthkeycloak#8]
First, let me thank you for this plugin.

I got this errors on first authentication:
`
Warning: Undefined array key "groups" in /var/www/html/lib/plugins/oauthkeycloak/action.php on line 46

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/plugins/oauthkeycloak/action.php:46) in /var/www/html/lib/plugins/oauth/Session.php on line 130

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/plugins/oauthkeycloak/action.php:46) in /var/www/html/inc/common.php on line 1871
`

After refreshing the tab the browser loads the docuwiki page home authenticated.
I am using:
DocuWiki:  2024-02-06a "Kaos" 
Keycloak: 24.0.3
Keycloak client setup attached:
[oath2-docuwiki.json](https://github.com/YoitoFes/dokuwiki-plugin-oauthkeycloak/files/15155396/oath2-docuwiki.json)

Any advice on how to remove the warnings? 

Regards

**Comment by YoitoFes** [comment]
Thank you for reporting issue.

#9 Updated the plugin to remove the wanings.

Would you try the latest version and confirm the dokuwiki logs?

Thank you.

**Comment by spacecake** [comment]
No more warnings.
There appears to be no other issue.

Thank you.
